### ISSUE TITLE
Cannot install latest release without downgrading YARL

### ISSUE THREAD

**Issue by tpdownes** [conda-forge/google-cloud-storage-feedstock#63]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

On MacOS (Intel 64), I am either forced to use an old version of `google-cloud-storage==1.19.0` or I have to downgrade `yarl` to an older release. This traces to [version pinning for yarl in the requirements][yarlreqs].

Is this version pinning still necessary? I am not sure where it's coming from since a quick search does not suggest it is a direct dependency of google-cloud-storage now (1.42) or then (1.19).

[yarlreqs]: https://github.com/conda-forge/google-cloud-storage-feedstock/blob/384d25e5056d5c07bb72f3cff00d4bd551c09902/recipe/meta.yaml#L29-L30

```shell
$ conda install google-cloud-storage==1.42
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/tpdownes/local/miniconda3/envs/default

  added / updated specs:
    - google-cloud-storage==1.42


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    google-cloud-storage-1.42.0|     pyh6c4a22f_0          73 KB  conda-forge
    google-crc32c-1.1.2        |   py39ha7afe54_0          22 KB  conda-forge
    google-resumable-media-2.1.0|     pyh6c4a22f_0          41 KB  conda-forge
    libcrc32c-1.1.2            |       he49afe7_0          20 KB  conda-forge
    yarl-1.5.1                 |   py39hb5aae12_0         132 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         287 KB

The following NEW packages will be INSTALLED:

  google-cloud-stor~ conda-forge/noarch::google-cloud-storage-1.42.0-pyh6c4a22f_0
  google-crc32c      conda-forge/osx-64::google-crc32c-1.1.2-py39ha7afe54_0
  google-resumable-~ conda-forge/noarch::google-resumable-media-2.1.0-pyh6c4a22f_0
  libcrc32c          conda-forge/osx-64::libcrc32c-1.1.2-he49afe7_0

The following packages will be DOWNGRADED:

  yarl                                 1.7.0-py39h89e85a6_0 --> 1.5.1-py39hb5aae12_0
```

**Comment by tpdownes** [comment]
This gets to me to an OK point:

```yaml
conda install google-cloud-storage~=1.42
conda update --all
```

because it leaves me with YARL permanently downgraded (since I don't know what YARL is, I am blissfully ignorant).

**Comment by tswast** [comment]
Supposedly https://github.com/conda-forge/aiohttp-feedstock/issues/43 has been resolved. We can try removing this pin.
